build(vos): point setuptools, tox and CI at the libs/vos layout
- setup.py builds from src/ and ships only package data, not tests
- pytest collects tests/ and skips tests/integration and
  tests/acceptance unless asked; the integration marker is registered
- tox and flake8 run on src and tests; integration tests stay out of
  the style check as before
- cibuild.yml and the README use libs/vos

diff --git a/.github/workflows/cibuild.yml b/.github/workflows/cibuild.yml
--- a/.github/workflows/cibuild.yml
+++ b/.github/workflows/cibuild.yml
@@ -20,7 +20,7 @@ jobs:
       - name: Install tox
         run: python -m pip install --upgrade tox
       - name: egg-info vos
-        run: cd vos && tox -e egg_info
+        run: cd libs/vos && tox -e egg_info
 
   tests:
     needs: egginfo
@@ -47,7 +47,7 @@ jobs:
         # add py and remove the "." from python-version in order to get the tox_target
         tox_target=$(echo py${{matrix.python-version}} | sed 's/\.//')
         echo "Tox target: " $tox_target
-        cd ${{ matrix.package }} && tox -e $tox_target 
+        cd libs/${{ matrix.package }} && tox -e $tox_target
 
   style_n_coverage:
     runs-on: ubuntu-latest
@@ -63,11 +63,11 @@ jobs:
       - name: Install tox
         run: python -m pip install --upgrade tox
       - name: checkstyle & coverage vos
-        run: cd vos && tox -e checkstyle && tox -e cov
+        run: cd libs/vos && tox -e checkstyle && tox -e cov
       - name: Upload coverage to codecov
         uses: codecov/codecov-action@v4
         with:
-          files: ./vos/coverage.xml
+          files: ./libs/vos/coverage.xml
        
   build-n-publish:
     name: Build and publish to PyPI
@@ -92,18 +92,18 @@ jobs:
       run: |
         echo ${{ env.repo_name }}
         echo ${{ env.repo_version }}
-        cd ${{ env.repo_name }} || (echo "Invalid release tag. Repo not found: ${{ env.repo_name }}" && exit -1)
+        cd libs/${{ env.repo_name }} || (echo "Invalid release tag. Repo not found: ${{ env.repo_name }}" && exit -1)
         sed 's/ //g' setup.cfg | grep "^version=${{ env.repo_version }}" || (echo "Version in tag ${{ env.repo_version }} does not match version in setup.cfg" && exit -1)
     - name: Install dependencies
       run: |
-        cd ${{ env.repo_name }}
+        cd libs/${{ env.repo_name }}
         python -m pip install --upgrade pip
         pip install setuptools wheel
     - name: Install package
       run: |
-        cd ${{ env.repo_name }}
+        cd libs/${{ env.repo_name }}
         python setup.py sdist bdist_wheel
     - name: Publish package distributions to PyPI
       uses: pypa/gh-action-pypi-publish@release/v1
       with:
-        packages-dir: ${{ env.repo_name }}/dist/
+        packages-dir: libs/${{ env.repo_name }}/dist/
